# Generated by Django 3.2.15 on 2022-09-19 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Покупатель",
                    ),
                ),
                (
                    "items",
                    models.ManyToManyField(
                        related_name="items",
                        to="market.Item",
                        verbose_name="покупки в корзине",
                    ),
                ),
            ],
            options={
                "verbose_name": ("Корзина",),
                "verbose_name_plural": "Корзины",
                "ordering": ["-id"],
            },
        ),
    ]
