# Generated by Django 3.2.15 on 2022-09-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_auto_20220919_1123"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="quantity",
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
