# Generated by Django 3.2.15 on 2022-09-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0006_auto_20220919_1351"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="discount",
            name="percent_off",
        ),
        migrations.AddField(
            model_name="discount",
            name="coupon",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
