# Generated by Django 3.2.15 on 2022-09-19 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payment", "0008_alter_order_discount"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="discount",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterField(
            model_name="order",
            name="buyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="discount",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discount",
                to="payment.discount",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="items",
            field=models.ManyToManyField(
                related_name="items", through="payment.ItemInCart", to="market.Item"
            ),
        ),
    ]
